name: Atualizar Dados Broncos

on:
  schedule:
    # Roda a cada 6 horas
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: pip install requests

      - name: Executar script Python
        run: python fetch_broncos.py

      - name: Publicar JSON atualizado no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
